prompts:
  themes_prompt: >
    You are a qualitative researcher with expertise in mental health. Your task is to perform 
    inductive coding on a set of Reddit posts from mental health subreddits.
    
    I'll provide you with {batch_size} posts. For each batch, please:
    1. Identify the main themes present across the posts
    2. For each theme, provide a name, description, and example indicators
    
    Here are the posts:
    
    {posts}
    
    Based on these posts, identify 2 to 4 major themes that emerge from the data. For each theme:
    1. Provide a clear name
    2. Write a 1-2 sentence description
    3. List 2-3 key indicators or signals of this theme
    4. Provide brief examples from the posts
    
    Format your response as a JSON object with the following structure:
    ```json
    {{
      "themes": [
        {{
          "name": "Theme name",
          "description": "Brief description",
          "indicators": ["indicator1", "indicator2", "indicator3"],
          "examples": ["example1", "example2"]
        }}
      ]
    }}
    ```
  consolidate_prompt: >
    You are a qualitative researcher consolidating themes identified across multiple batches of data.

    You have previously analyzed several batches of Reddit posts from mental health subreddits and identified themes in each batch. 

    Your task is to create a unified codebook by consolidating similar themes.

    Here are the themes identified in each batch:

    {batch_themes}

    Please create a consolidated codebook with 5-8 major themes that cover the patterns seen across all batches.
    For each theme in your consolidated codebook:
    1. Provide a clear name
    2. Write a concise description
    3. List key indicators or signals of this theme
    4. Note which batch themes this consolidated theme incorporates

    Format your response as a JSON object with the following structure:
    ```json
    {{
      "codebook": [
       {{
          "code": "Code name",
          "description": "Description",
          "indicators": ["indicator1", "indicator2", "indicator3"],
          "source_themes": ["Batch 1: Theme X", "Batch 3: Theme Y"]
        }}
      ]
    }}
    ```
  deduction_prompt: >
    You are analyzing a Reddit post from a mental health subreddit.
    Apply the following codebook to the post:

    CODEBOOK:
    {codes_list}

    POST:
    Title: {post_title}
    Content: {post_text}

    Assign the most relevant codes to this post. For each code you assign, provide:
    1. The code name
    2. A confidence score (1-5, where 5 is highest confidence)
    3. Brief reasoning for why this code applies
    4. Specific text from the post that indicates this code

    A post may have multiple codes or no codes at all. Only assign codes if they are clearly present.

    Format your response as a JSON object:
    ```json
    {{
      "assigned_codes": [
        {{
          "code": "Code name",
          "confidence": 4,
          "reasoning": "Why this code applies",
          "evidence": "Quote from post"
        }}
      ]
    }}
    ```
